import './globals.css'
import {Auth0Provider} from "@auth0/auth0-react";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <Auth0Provider
            domain={process.env.AUTH0_DOMAIN!}
            clientId={process.env.AUTH0_CLIENT_ID!}
            authorizationParams={{
                redirect_uri: window.location.origin
            }}
        >
            <html lang="en">
                <body>{children}</body>
            </html>
        </Auth0Provider>
    )
}
